Bug Fix and Performance Update
1. fillBoard is now a function

2. the order of functions and const were reordered from top to bottom like so:

fillBoard>>printBoard>>placeMove>>victoryCheck>>game

3. move p was removed

4. player1 boolean is now decided with a ternary operator

5. victoryCheck no longer uses a boolean array, and instead uses 7 boolean values. Those boolean values if all true break the for loop using a NOT gate

6. victoryCheck no longer checks for wins upwards

7. fixes printBoard printing incorrectly and renamed board inside of printBoard to boardArr because of compilation issues

Note: run "npm ls readline-sync" on your console if youre getting the error:

Error: Cannot find module 'readline-sync'